# This is a basic workflow to help you get started with Actions

name: TestWFPullRequest

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    paths:
      - '**.js'
      - '!docs/**'
      - '**.yml'
    branches: 
      - 'main'
      - 'release/**'
      - '!dev/**'
  pull_request:
    types:
      - opened
      - closed
      - synchronize
      - labeled
      - unlabeled
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    permissions:
      checks: write
      pull-requests: write
      contents: write
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: mheap/github-action-required-labels@v4
        with:
          mode: exactly
          count: 0
          labels: "không CI cái này"
      - uses: actions/checkout@v2
      - run: npm install  
      - uses: ArtiomTr/jest-coverage-report-action@v2      
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-step: none
      
      